on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job1 - step1
        run: echo "hello from job1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: job2 - step1
        run: echo "Hello from job2, after job1"