name: Build and deploy example
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Building
        run: echo "Building"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Deploying
        run: echo "Deploying"